# Generated by Django 3.1.2 on 2020-10-07 19:32

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='product-images')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('expiry_date', models.DateTimeField(default=apps.products.models.default_expirydate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
